name: Build WordPress Plugin ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v3

      - name: Set plugin slug
        run: echo "PLUGIN_SLUG=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Create ZIP package
        run: |
          mkdir -p build
          zip -r "build/${{ env.PLUGIN_SLUG }}.zip" . -x "*.git*" -x "build/*" -x ".github/*"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_SLUG }}-zip
          path: build/${{ env.PLUGIN_SLUG }}.zip

      - name: Create GitHub Release (if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/${{ env.PLUGIN_SLUG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
